typography_spectrum: 0.5349459680728614
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.017152681713923812
  lightness: 0.377532450016588
  saturation: 0.6488638196606189
  rhythmicContrast: 0.8601224170997739
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.00578989670611918
analytics:
  google: null
  facebook: null
  twitter: null
name: hello-hello
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hello new editor
description: 'all in place, hä?'
purpose: []
